# Use a imagem oficial do PostgreSQL
FROM postgres:latest

# Define variáveis de ambiente padrão para o banco
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=ffase2-microfrontend
ENV POSTGRES_DB=fiap-fase2-microfront

EXPOSE 5432