FROM node:20-alpine AS build

WORKDIR /app

# Copia os arquivos
COPY ../package.json ../package-lock.json ./
COPY ../apps/remote-app ./apps/remote-app/

RUN npm install

WORKDIR /app/apps/remote-app

RUN npm run build

# Etapa 2: Servir o build em produção
FROM node:20-alpine AS serve

WORKDIR /app

COPY --from=build /app/apps/remote-app/dist /app/apps/remote-app

RUN npm install -g serve

EXPOSE 3002

CMD ["serve", "-s", "/app/apps/remote-app", "-p", "3002"]
